/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.unifimes.Aula17.Exemplo01;

/**
 *
 * @author alencarburiti
 */
public class FilaPaciente extends javax.swing.JFrame {

    int posicao = 0;
    Paciente paciente = new Paciente();

    /**
     * Creates new form FilaPacientes
     */
    public FilaPaciente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paciente3 = new javax.swing.JTextField();
        paciente2 = new javax.swing.JTextField();
        paciente1 = new javax.swing.JTextField();
        paciente4 = new javax.swing.JTextField();
        paciente5 = new javax.swing.JTextField();
        paciente6 = new javax.swing.JTextField();
        paciente7 = new javax.swing.JTextField();
        paciente8 = new javax.swing.JTextField();
        paciente9 = new javax.swing.JTextField();
        paciente10 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jlQuantidade = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        paciente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paciente2ActionPerformed(evt);
            }
        });

        paciente9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paciente9ActionPerformed(evt);
            }
        });

        jButton1.setText("Inserir (Fim da Fila)");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Remover (Início da Fila)");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Lista de Pacientes em Espera");

        jlQuantidade.setText("Quantidade de pacientes na fila: 0");

        jButton3.setText("Mostrar");
        jButton3.setToolTipText("");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(paciente2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(paciente3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(paciente4)
                                    .addComponent(paciente5)
                                    .addComponent(paciente6)
                                    .addComponent(paciente7)
                                    .addComponent(paciente8)
                                    .addComponent(paciente9)
                                    .addComponent(paciente10, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(paciente1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlQuantidade)))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(paciente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(paciente2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paciente3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paciente4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paciente5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(paciente6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(paciente7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paciente8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paciente9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paciente10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jlQuantidade)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void paciente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paciente2ActionPerformed
        
        // TODO add your handling code here:
    }//GEN-LAST:event_paciente2ActionPerformed

    private void paciente9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paciente9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paciente9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        
        // Vai estar liberad o campo e bloqueia em seguida
        if (paciente.fim == -1 ){
            paciente.adicionar(paciente1.getText());
            paciente1.setEditable(false);   
            jlQuantidade.setText("Quantidade de pacientes na fila: " + paciente.qtdeElementos);
        } else if (paciente.qtdeElementos == 0 && !paciente1.isEditable() &&  paciente1.getText().isEmpty()){
            paciente.adicionar(paciente2.getText());
            paciente2.setEditable(false);   
            jlQuantidade.setText("Quantidade de pacientes na fila: " + paciente.qtdeElementos);
        } else if (paciente.qtdeElementos == 1){
            paciente.adicionar(paciente3.getText());
            paciente3.setEditable(false);   
            jlQuantidade.setText("Quantidade de pacientes na fila: " + paciente.qtdeElementos);
        } 
        //paciente.adicionar(paciente1.getText());
        /*        if (!paciente1.isEditable() && paciente1.getText().isEmpty()) {
            paciente1.setEditable(true);            
            
            
            
            
        } else if (!paciente2.isEditable() && paciente2.getText().isEmpty() && !paciente1.getText().isEmpty()) {
            paciente2.setEditable(true);
            posicao += 1;
            jlQuantidade.setText("Quantidade de pacientes na fila: " + posicao);
        } else if (!paciente3.isEditable() && paciente3.getText().isEmpty() && !paciente2.getText().isEmpty()) {
            paciente3.setEditable(true);
            posicao += 1;
            jlQuantidade.setText("Quantidade de pacientes na fila: " + posicao);
        } else if (!paciente4.isEditable() && paciente4.getText().isEmpty() && !paciente3.getText().isEmpty()) {
            paciente4.setEditable(true);
            posicao += 1;
            jlQuantidade.setText("Quantidade de pacientes na fila: " + posicao);
        } else if (!paciente5.isEditable() && paciente5.getText().isEmpty() && !paciente4.getText().isEmpty()) {
            paciente5.setEditable(true);
            posicao += 1;
            jlQuantidade.setText("Quantidade de pacientes na fila: " + posicao);
        } else if (!paciente6.isEditable() && paciente6.getText().isEmpty() && !paciente5.getText().isEmpty()) {
            paciente6.setEditable(true);
            posicao += 1;
            jlQuantidade.setText("Quantidade de pacientes na fila: " + posicao);
        } else if (!paciente7.isEditable() && paciente7.getText().isEmpty() && !paciente6.getText().isEmpty()) {
            paciente7.setEditable(true);
            posicao += 1;
            jlQuantidade.setText("Quantidade de pacientes na fila: " + posicao);
        } else if (!paciente8.isEditable() & paciente8.getText().isEmpty() && !paciente7.getText().isEmpty()) {
            paciente8.setEditable(true);
            posicao += 1;
            jlQuantidade.setText("Quantidade de pacientes na fila: " + posicao);
        } else if (!paciente9.isEditable() & paciente9.getText().isEmpty() && !paciente8.getText().isEmpty()) {
            paciente9.setEditable(true);
            posicao += 1;
            jlQuantidade.setText("Quantidade de pacientes na fila: " + posicao);
        } else if (!paciente10.isEditable() & paciente10.getText().isEmpty() && !paciente9.getText().isEmpty()) {
            paciente10.setEditable(true);
            posicao += 1;
            jlQuantidade.setText("Quantidade de pacientes na fila: " + posicao);
        }
        */
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (paciente1.isEditable() && !paciente1.getText().isEmpty()) {
            paciente1.setText("");
            paciente1.setEditable(false);
            posicao -= 1;
            jlQuantidade.setText("Quantidade de pacientes na fila: " + posicao);
        } else if (paciente2.isEditable() && !paciente2.getText().isEmpty() && !paciente1.getText().isEmpty()) {
            paciente2.setText("");
            paciente2.setEditable(false);
            posicao -= 1;
            jlQuantidade.setText("Quantidade de pacientes na fila: " + posicao);
        } else if (paciente3.isEditable() && !paciente3.getText().isEmpty() && !paciente2.getText().isEmpty()) {
            paciente3.setText("");
            paciente3.setEditable(false);
            posicao -= 1;
            jlQuantidade.setText("Quantidade de pacientes na fila: " + posicao);
        } else if (!paciente4.isEditable() && paciente4.getText().isEmpty() && !paciente3.getText().isEmpty()) {
            paciente4.setEditable(true);
            posicao += 1;
            jlQuantidade.setText("Quantidade de pacientes na fila: " + posicao);
        } else if (!paciente5.isEditable() && paciente5.getText().isEmpty() && !paciente4.getText().isEmpty()) {
            paciente5.setEditable(true);
            posicao += 1;
            jlQuantidade.setText("Quantidade de pacientes na fila: " + posicao);
        } else if (!paciente6.isEditable() && paciente6.getText().isEmpty() && !paciente5.getText().isEmpty()) {
            paciente6.setEditable(true);
            posicao += 1;
            jlQuantidade.setText("Quantidade de pacientes na fila: " + posicao);
        } else if (!paciente7.isEditable() && paciente7.getText().isEmpty() && !paciente6.getText().isEmpty()) {
            paciente7.setEditable(true);
            posicao += 1;
            jlQuantidade.setText("Quantidade de pacientes na fila: " + posicao);
        } else if (!paciente8.isEditable() & paciente8.getText().isEmpty() && !paciente7.getText().isEmpty()) {
            paciente8.setEditable(true);
            posicao += 1;
            jlQuantidade.setText("Quantidade de pacientes na fila: " + posicao);
        } else if (!paciente9.isEditable() & paciente9.getText().isEmpty() && !paciente8.getText().isEmpty()) {
            paciente9.setEditable(true);
            posicao += 1;
            jlQuantidade.setText("Quantidade de pacientes na fila: " + posicao);
        } else if (!paciente10.isEditable() & paciente10.getText().isEmpty() && !paciente9.getText().isEmpty()) {
            paciente10.setEditable(true);
            posicao += 1;
            jlQuantidade.setText("Quantidade de pacientes na fila: " + posicao);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        paciente.mostrar();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FilaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FilaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FilaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FilaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FilaPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jlQuantidade;
    private javax.swing.JTextField paciente1;
    private javax.swing.JTextField paciente10;
    private javax.swing.JTextField paciente2;
    private javax.swing.JTextField paciente3;
    private javax.swing.JTextField paciente4;
    private javax.swing.JTextField paciente5;
    private javax.swing.JTextField paciente6;
    private javax.swing.JTextField paciente7;
    private javax.swing.JTextField paciente8;
    private javax.swing.JTextField paciente9;
    // End of variables declaration//GEN-END:variables
}
